### PR TITLE
Add support for non-conforming nullish values

### PR DESCRIPTION
**Pull request by remcohaszing**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Some unified plugins generate such values.

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]
Once CI passes.
LGTM, thanks @remcohaszing!

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Do you want me to release this immediately? Are you planning further work?

**Comment by remcohaszing** [comment]
IMO this may be released immediately. I'm not planning to make further changes to this repo atm.

**Comment by wooorm** [comment]
Thanks, released in [`1.0.2`](https://github.com/syntax-tree/unist-util-lsp/releases/tag/1.0.2)!

**Pull request merged**
